// This file is auto-generated by Supabase CLI.
// Run: pnpm db:generate-types to regenerate after schema changes.
// DO NOT edit manually.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]

// Row types extracted to top-level to avoid circular references inside the Database object
export type ProfileRow = {
  id: string
  membership_number: string | null
  first_name: string
  last_name: string
  first_name_en: string | null
  last_name_en: string | null
  graduation_year: number | null
  department: string | null
  current_position: string | null
  current_company: string | null
  industry: string | null
  bio: string | null
  bio_en: string | null
  avatar_url: string | null
  cover_url: string | null
  linkedin_url: string | null
  website_url: string | null
  phone: string | null
  city: string | null
  country: string | null
  is_mentor: boolean
  phone_public: boolean
  email_public: boolean
  membership_status: 'active' | 'inactive' | 'suspended'
  role: 'super_admin' | 'admin' | 'verified_member' | 'basic_member'
  language_pref: 'el' | 'en'
  onboarding_completed: boolean
  search_vector: string | null
  created_at: string
  updated_at: string
}

export type ProfileInsert = Omit<ProfileRow, 'created_at' | 'updated_at' | 'search_vector'>
export type ProfileUpdate = Partial<ProfileInsert>

// ---- Businesses ----

export type BusinessRow = {
  id: string
  owner_id: string
  name: string
  name_en: string | null
  description: string | null
  description_en: string | null
  category: string | null
  industry: string | null
  logo_url: string | null
  website_url: string | null
  email: string | null
  phone: string | null
  address: string | null
  city: string | null
  country: string | null
  linkedin_url: string | null
  instagram_url: string | null
  is_verified: boolean
  is_active: boolean
  search_vector: string | null
  created_at: string
  updated_at: string
}

export type BusinessInsert = Omit<BusinessRow, 'id' | 'created_at' | 'updated_at' | 'search_vector'>
export type BusinessUpdate = Partial<BusinessInsert>

// ---- Benefits ----

export type BenefitRow = {
  id: string
  title: string
  title_en: string | null
  description: string | null
  description_en: string | null
  category: string
  partner_name: string
  partner_logo_url: string | null
  discount_text: string | null
  terms: string | null
  terms_en: string | null
  redemption_code: string | null
  redemption_url: string | null
  is_active: boolean
  valid_from: string
  valid_until: string | null
  max_redemptions: number | null
  redemption_count: number
  requires_verified_member: boolean
  created_by: string | null
  created_at: string
  updated_at: string
}

export type BenefitInsert = Omit<BenefitRow, 'id' | 'redemption_count' | 'created_at' | 'updated_at'>
export type BenefitUpdate = Partial<BenefitInsert>

export type BenefitRedemptionRow = {
  id: string
  benefit_id: string
  user_id: string
  redeemed_at: string
  verification_code: string
  verified_at: string | null
}

export type BenefitRedemptionInsert = Omit<BenefitRedemptionRow, 'id' | 'redeemed_at' | 'verification_code' | 'verified_at'>

// ---- Events ----

export type EventRow = {
  id: string
  title: string
  title_en: string | null
  description: string | null
  description_en: string | null
  type: 'in_person' | 'virtual' | 'hybrid'
  status: 'draft' | 'published' | 'cancelled' | 'completed'
  start_date: string
  end_date: string
  location: string | null
  location_url: string | null
  virtual_url: string | null
  cover_url: string | null
  capacity: number | null
  rsvp_count: number
  waitlist_count: number
  is_public: boolean
  created_by: string | null
  created_at: string
  updated_at: string
}

export type EventInsert = Omit<EventRow, 'id' | 'rsvp_count' | 'waitlist_count' | 'created_at' | 'updated_at'>
export type EventUpdate = Partial<EventInsert>

export type EventRsvpRow = {
  id: string
  event_id: string
  user_id: string
  status: 'attending' | 'waitlist' | 'cancelled'
  created_at: string
  updated_at: string
}

export type EventRsvpInsert = {
  event_id: string
  user_id: string
  status?: 'attending' | 'waitlist' | 'cancelled'
}

// ---- Messaging ----

export type ConversationRow = {
  id: string
  title: string | null
  last_message_at: string
  last_message_preview: string | null
  created_at: string
  updated_at: string
}

export type ConversationInsert = {
  title?: string | null
}

export type ConversationParticipantRow = {
  conversation_id: string
  user_id: string
  joined_at: string
  last_read_at: string
}

export type ConversationParticipantInsert = {
  conversation_id: string
  user_id: string
  last_read_at?: string
}

export type MessageRow = {
  id: string
  conversation_id: string
  sender_id: string | null
  content: string
  is_deleted: boolean
  created_at: string
}

export type MessageInsert = {
  conversation_id: string
  sender_id: string
  content: string
}

// ---- Notifications ----

export type NotificationRow = {
  id: string
  user_id: string
  type: string
  title: string
  body: string | null
  link: string | null
  is_read: boolean
  created_at: string
}

export type NotificationInsert = Omit<NotificationRow, 'id' | 'created_at'>
export type NotificationUpdate = Partial<Pick<NotificationRow, 'is_read'>>

// ---- Gallery ----

export type GalleryAlbumRow = {
  id: string
  title: string
  title_en: string | null
  description: string | null
  description_en: string | null
  cover_photo_url: string | null
  photo_count: number
  is_published: boolean
  event_id: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export type GalleryAlbumInsert = Omit<GalleryAlbumRow, 'id' | 'photo_count' | 'created_at' | 'updated_at'>
export type GalleryAlbumUpdate = Partial<GalleryAlbumInsert>

export type GalleryPhotoRow = {
  id: string
  album_id: string
  storage_path: string
  url: string
  thumbnail_url: string | null
  caption: string | null
  caption_en: string | null
  width: number | null
  height: number | null
  file_size: number | null
  is_approved: boolean
  uploaded_by: string | null
  created_at: string
  updated_at: string
}

export type GalleryPhotoInsert = {
  album_id: string
  storage_path: string
  url: string
  uploaded_by: string | null
  is_approved?: boolean
  thumbnail_url?: string | null
  caption?: string | null
  caption_en?: string | null
  width?: number | null
  height?: number | null
  file_size?: number | null
}
export type GalleryPhotoUpdate = Partial<GalleryPhotoInsert>

// ---- Jobs ----

export type JobType = 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'volunteer'
export type JobStatus = 'open' | 'closed' | 'draft'

export type JobRow = {
  id: string
  posted_by: string | null
  title: string
  title_en: string | null
  company: string
  description: string | null
  description_en: string | null
  type: JobType
  status: JobStatus
  location: string | null
  is_remote: boolean
  salary_range: string | null
  apply_url: string | null
  apply_email: string | null
  industry: string | null
  expires_at: string | null
  created_at: string
  updated_at: string
}

export type JobInsert = Omit<JobRow, 'id' | 'created_at' | 'updated_at'>
export type JobUpdate = Partial<JobInsert>

export type SavedJobRow = {
  user_id: string
  job_id: string
  saved_at: string
}

export type SavedJobInsert = {
  user_id: string
  job_id: string
}

// ---- Mentorship ----

export type MentorshipStatus = 'pending' | 'accepted' | 'declined' | 'active' | 'completed' | 'cancelled'

export type MentorshipRow = {
  id: string
  mentor_id: string
  mentee_id: string
  status: MentorshipStatus
  goals: string | null
  message: string | null
  mentor_notes: string | null
  mentee_feedback: string | null
  mentor_feedback: string | null
  started_at: string | null
  completed_at: string | null
  created_at: string
  updated_at: string
}

export type MentorshipInsert = {
  mentor_id: string
  mentee_id: string
  goals?: string | null
  message?: string | null
}

export type MentorshipUpdate = Partial<Pick<MentorshipRow,
  'status' | 'goals' | 'mentor_notes' | 'mentee_feedback' | 'mentor_feedback'
>>

// ---- Announcements ----

export type AnnouncementRow = {
  id: string
  title: string
  title_en: string | null
  body: string
  body_en: string | null
  type: string
  cover_url: string | null
  is_published: boolean
  published_at: string | null
  created_by: string | null
  created_at: string
  updated_at: string
}

export type AnnouncementInsert = Omit<AnnouncementRow, 'id' | 'created_at' | 'updated_at'>
export type AnnouncementUpdate = Partial<AnnouncementInsert>

// ---- Success Stories ----

export type SuccessStoryRow = {
  id: string
  user_id: string
  title: string
  title_en: string | null
  content: string
  content_en: string | null
  cover_url: string | null
  is_approved: boolean
  created_at: string
  updated_at: string
}

export type SuccessStoryInsert = Omit<SuccessStoryRow, 'id' | 'created_at' | 'updated_at'>
export type SuccessStoryUpdate = Partial<SuccessStoryInsert>

// ---- Polls ----

export type PollRow = {
  id: string
  question: string
  question_en: string | null
  created_by: string | null
  closes_at: string | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export type PollInsert = Omit<PollRow, 'id' | 'created_at' | 'updated_at'>
export type PollUpdate = Partial<PollInsert>

export type PollOptionRow = {
  id: string
  poll_id: string
  text: string
  text_en: string | null
  vote_count: number
  position: number
}

export type PollOptionInsert = Omit<PollOptionRow, 'id' | 'vote_count'>

export type PollVoteRow = {
  poll_id: string
  option_id: string
  user_id: string
  voted_at: string
}

export type PollVoteInsert = {
  poll_id: string
  option_id: string
  user_id: string
}

// ---- Groups ----

export type GroupRow = {
  id: string
  name: string
  name_en: string | null
  description: string | null
  description_en: string | null
  cover_url: string | null
  is_private: boolean
  member_count: number
  created_by: string | null
  created_at: string
  updated_at: string
}

export type GroupInsert = Omit<GroupRow, 'id' | 'member_count' | 'created_at' | 'updated_at'>
export type GroupUpdate = Partial<GroupInsert>

export type GroupMemberRow = {
  group_id: string
  user_id: string
  role: string
  joined_at: string
}

export type GroupMemberInsert = {
  group_id: string
  user_id: string
  role?: string
}

export type GroupPostRow = {
  id: string
  group_id: string
  user_id: string
  content: string
  is_deleted: boolean
  created_at: string
  updated_at: string
}

export type GroupPostInsert = {
  group_id: string
  user_id: string
  content: string
}

export type GroupPostUpdate = Partial<Pick<GroupPostRow, 'content' | 'is_deleted'>>

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: ProfileRow
        Insert: ProfileInsert
        Update: ProfileUpdate
        Relationships: []
      }
      businesses: {
        Row: BusinessRow
        Insert: BusinessInsert
        Update: BusinessUpdate
        Relationships: [
          {
            foreignKeyName: 'businesses_owner_id_fkey'
            columns: ['owner_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      benefits: {
        Row: BenefitRow
        Insert: BenefitInsert
        Update: BenefitUpdate
        Relationships: [
          {
            foreignKeyName: 'benefits_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      benefit_redemptions: {
        Row: BenefitRedemptionRow
        Insert: BenefitRedemptionInsert
        Update: Partial<BenefitRedemptionInsert>
        Relationships: [
          {
            foreignKeyName: 'benefit_redemptions_benefit_id_fkey'
            columns: ['benefit_id']
            isOneToOne: false
            referencedRelation: 'benefits'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'benefit_redemptions_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      events: {
        Row: EventRow
        Insert: EventInsert
        Update: EventUpdate
        Relationships: [
          {
            foreignKeyName: 'events_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      event_rsvps: {
        Row: EventRsvpRow
        Insert: EventRsvpInsert
        Update: Partial<EventRsvpInsert>
        Relationships: [
          {
            foreignKeyName: 'event_rsvps_event_id_fkey'
            columns: ['event_id']
            isOneToOne: false
            referencedRelation: 'events'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'event_rsvps_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      gallery_albums: {
        Row: GalleryAlbumRow
        Insert: GalleryAlbumInsert
        Update: GalleryAlbumUpdate
        Relationships: [
          {
            foreignKeyName: 'gallery_albums_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      gallery_photos: {
        Row: GalleryPhotoRow
        Insert: GalleryPhotoInsert
        Update: GalleryPhotoUpdate
        Relationships: [
          {
            foreignKeyName: 'gallery_photos_album_id_fkey'
            columns: ['album_id']
            isOneToOne: false
            referencedRelation: 'gallery_albums'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'gallery_photos_uploaded_by_fkey'
            columns: ['uploaded_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      conversations: {
        Row: ConversationRow
        Insert: ConversationInsert
        Update: Partial<ConversationInsert>
        Relationships: []
      }
      conversation_participants: {
        Row: ConversationParticipantRow
        Insert: ConversationParticipantInsert
        Update: Partial<ConversationParticipantInsert>
        Relationships: [
          {
            foreignKeyName: 'conversation_participants_conversation_id_fkey'
            columns: ['conversation_id']
            isOneToOne: false
            referencedRelation: 'conversations'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'conversation_participants_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      messages: {
        Row: MessageRow
        Insert: MessageInsert
        Update: Partial<MessageInsert>
        Relationships: [
          {
            foreignKeyName: 'messages_conversation_id_fkey'
            columns: ['conversation_id']
            isOneToOne: false
            referencedRelation: 'conversations'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'messages_sender_id_fkey'
            columns: ['sender_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      notifications: {
        Row: NotificationRow
        Insert: NotificationInsert
        Update: NotificationUpdate
        Relationships: [
          {
            foreignKeyName: 'notifications_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      jobs: {
        Row: JobRow
        Insert: JobInsert
        Update: JobUpdate
        Relationships: [
          {
            foreignKeyName: 'jobs_posted_by_fkey'
            columns: ['posted_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      saved_jobs: {
        Row: SavedJobRow
        Insert: SavedJobInsert
        Update: Partial<SavedJobInsert>
        Relationships: [
          {
            foreignKeyName: 'saved_jobs_job_id_fkey'
            columns: ['job_id']
            isOneToOne: false
            referencedRelation: 'jobs'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'saved_jobs_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      mentorships: {
        Row: MentorshipRow
        Insert: MentorshipInsert
        Update: MentorshipUpdate
        Relationships: [
          {
            foreignKeyName: 'mentorships_mentor_id_fkey'
            columns: ['mentor_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          },
          {
            foreignKeyName: 'mentorships_mentee_id_fkey'
            columns: ['mentee_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      announcements: {
        Row: AnnouncementRow
        Insert: AnnouncementInsert
        Update: AnnouncementUpdate
        Relationships: [
          {
            foreignKeyName: 'announcements_created_by_fkey'
            columns: ['created_by']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      success_stories: {
        Row: SuccessStoryRow
        Insert: SuccessStoryInsert
        Update: SuccessStoryUpdate
        Relationships: [
          {
            foreignKeyName: 'success_stories_user_id_fkey'
            columns: ['user_id']
            isOneToOne: false
            referencedRelation: 'profiles'
            referencedColumns: ['id']
          }
        ]
      }
      polls: {
        Row: PollRow
        Insert: PollInsert
        Update: PollUpdate
        Relationships: []
      }
      poll_options: {
        Row: PollOptionRow
        Insert: PollOptionInsert
        Update: Partial<PollOptionInsert>
        Relationships: [
          {
            foreignKeyName: 'poll_options_poll_id_fkey'
            columns: ['poll_id']
            isOneToOne: false
            referencedRelation: 'polls'
            referencedColumns: ['id']
          }
        ]
      }
      poll_votes: {
        Row: PollVoteRow
        Insert: PollVoteInsert
        Update: Partial<PollVoteInsert>
        Relationships: [
          {
            foreignKeyName: 'poll_votes_poll_id_fkey'
            columns: ['poll_id']
            isOneToOne: false
            referencedRelation: 'polls'
            referencedColumns: ['id']
          }
        ]
      }
      groups: {
        Row: GroupRow
        Insert: GroupInsert
        Update: GroupUpdate
        Relationships: []
      }
      group_members: {
        Row: GroupMemberRow
        Insert: GroupMemberInsert
        Update: Partial<GroupMemberInsert>
        Relationships: [
          {
            foreignKeyName: 'group_members_group_id_fkey'
            columns: ['group_id']
            isOneToOne: false
            referencedRelation: 'groups'
            referencedColumns: ['id']
          }
        ]
      }
      group_posts: {
        Row: GroupPostRow
        Insert: GroupPostInsert
        Update: GroupPostUpdate
        Relationships: [
          {
            foreignKeyName: 'group_posts_group_id_fkey'
            columns: ['group_id']
            isOneToOne: false
            referencedRelation: 'groups'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      membership_status: 'active' | 'inactive' | 'suspended'
      user_role: 'super_admin' | 'admin' | 'verified_member' | 'basic_member'
      language_pref: 'el' | 'en'
      event_status: 'draft' | 'published' | 'cancelled' | 'completed'
      event_type: 'in_person' | 'virtual' | 'hybrid'
      job_type: 'full_time' | 'part_time' | 'contract' | 'internship' | 'freelance' | 'volunteer'
      job_status: 'open' | 'closed' | 'draft'
      mentorship_status: 'pending' | 'accepted' | 'declined' | 'active' | 'completed' | 'cancelled'
    }
  }
}

export type Tables<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row']
export type Enums<T extends keyof Database['public']['Enums']> = Database['public']['Enums'][T]
